export const quotes = [
  "Cada día sin nicotina es una victoria. ¡Sigue adelante!",
  "Tu cuerpo te lo agradecerá, tu mente también. ¡Tú puedes!",
  "Respirar libremente vale más que cualquier cigarro.",
  "No estás renunciando a algo, estás ganando tu vida.",
  "Cada vez que dices no, te haces más fuerte.",
  "Dejarlo no es fácil, pero es lo mejor que puedes hacer por ti.",
  "Tu salud, tu futuro, tu decisión. ¡Eres capaz!",
  "No necesitas la nicotina para ser tú. Eres suficiente.",
  "Las ganas pasan, pero el orgullo de resistir se queda.",
  "Hoy elijas tu bienestar, mañana tu cuerpo te lo agradecerá.",
  "No estás solo. Cada paso es parte del progreso.",
  "Respirar sin humo es un regalo que te estás dando.",
  "Tu fuerza es más grande que cualquier adicción.",
  "Cada día limpio es una prueba de tu valentía.",
  "Cambia ansiedad por libertad. ¡Tú tienes el control!",
  "La vida sin humo es una vida más plena y feliz.",
  "Cada día sin fumar es un paso hacia una vida más saludable.",
  "La nicotina no define quién eres. Tú eres más fuerte que eso.",
  "Cada vez que resistes, te acercas más a tu meta.",
  "La libertad de dejar de fumar es un regalo que te haces a ti mismo.",  
  "Cada día sin fumar es una victoria personal.",
  "La vida es demasiado corta para desperdiciarla con humo.",
];
